contact_links:
  - name: New version of Minecraft or Sodium
    url: https://comp500.github.io/Indium/update%20when/???
    about: A new version of Minecraft or Sodium has been released, and Indium is not yet compatible.